### ISSUE TITLE
Direct usage with Falco

### ISSUE THREAD

**Issue by jemag** [sysdiglabs/aks-audit-log#4]
I know that this project is meant to be used with sysdig-agent, however sysdig-agent itself seems to use it partly for Falco rules. Therefore, I am wondering:
- Can this project be used directly with Falco installed on an AKS cluster (e.g.: replacing WebSinkURL by the URL of falco integrated web server)? I am not quite sure if Falco and sysdig-agent both consume the same format outputted by this project.
- I have not seen any LICENSE. Is the code of this project considered open source and its use free of any sysdig pricing?

**Comment by vicenteherrera** [comment]
Hi @jemag!

You are right, our first target was usage with Sysdig agent, but it should be compatible with Falco. It just sends the JSON of each individual Kubernetes event to the service.

We have added an Apache 2.0 license to make it clear that you can use it in that way. We are going to consult if we can find ways to better enable its usage with open-source Falco.

Please, let me know if you have been able to make it work with Falco, and send any additional questions you may have about that! ;-)

**Comment by jemag** [comment]
That is great news! I am a bit swamped at the moment, but I will definitely try to make a prototype in the coming weeks. I will report back afterwards.

**Comment by kko72** [comment]
Hi,

I have tried setting this up, but the audit-log-forwarder encounters a BadRequest error when sending the requests to the Falco websink endpoint:

`e75a9657 0 > **Error sending POST, retry 1, result: [BadRequest] System.Net.Http.HttpConnectionResponseContent`

It seems that the Content-Type header sent is set to `application/json; charset=utf-8` while Falco expects strictly `application/json` (crf. [webserver.cpp](https://github.com/falcosecurity/falco/blob/46425b392cc949b78d754c71875ad9a9c5121106/userspace/falco/webserver.cpp#L151))

It works as expected after fixing the header issue.

**Comment by jemag** [comment]
Completed on the falco side a while ago https://github.com/falcosecurity/falco/issues/1702
